{{- if .Values.tailscaleIngress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tailscale-{{ .Release.Name }}
  {{- if .Values.tailscaleIngress.funnel }}
  annotations:
    tailscale.com/funnel: "true"
  {{- end }}
spec:
  defaultBackend:
    service:
      name: {{ .Values.tailscaleIngress.serviceName }}
      port:
        number: {{ .Values.tailscaleIngress.servicePort }}
  ingressClassName: tailscale
  tls:
    - hosts:
        - {{ .Values.tailscaleIngress.host }}

{{- end }}